services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/aculei/aculei-be:main
    container_name: aculei-be
    ports:
      - "8888:8888"
    restart: on-failure
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - GIN_MODE=${GIN_MODE}
      - MONGO_URI=${MONGO_URI}
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
